services:
  app:
    image: digitalrootlabs/arte-marca:local
    build:
      context: ./
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.18
    restart: always
    env_file:
      - .env
    volumes:
      - pgsql_data:/var/lib/pgsql
volumes:
  pgsql_data:
